name: Heroku deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deploy_code_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: bump version and push tag
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: '1.0.0'
      - name: set node.js up
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install dependencies
        run: npm install
      - name: lint code
        run: npm run eslint
      - name: lint failed message
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: deploy code
        if: ${{ github.event_name == 'push' && false == contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY}}
          heroku_app_name: 'daily-slackbot'
          heroku-email: 'jukkaa@live.com'
      - name: job was suuccess message
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,author,took
          custom_payload: |
             {
               attachments: [{
                 text: `A new version was deployed to Heroku with commit ${process.env.AS_COMMIT} of ${process.env.AS_REPO} by ${process.env.AS_AUTHOR} and build took ${process.env.AS_TOOK}`
               }]
             }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
